### PR TITLE
Fix some help and `GetRequiredValue` issues

### LINKED ISSUE #2573: GetRequiredValue throws for implicit values
Currently, `Argument.GetRequiredValue` and `Option.GetRequiredValue` will throw `InvalidOperationException` when the argument or option wasn't actually parsed from command line input. For example:

```csharp
var option = new Option<bool>("-x");

var command = new RootCommand
{
    option
};

// the following throws: -x is required but was not provided
var value = command.Parse("").GetRequiredValue(option);
```

If `Option.DefaultValueFactory` is set, then the exception is not thrown. 

I believe the design of `GetValue` and `GetRequiredValue` should focus on whether the value for the symbol can be bound, including implicit and default values, regardless of whether a matching token was found on the parsed commandline. 

This could be the wrong intuition though. For `bool` it seems intuitive, and perhaps for `int` and other numeric types that default to `0`, but for more complex structs such as `DateTime`, as well as for reference types, this kind of behavior seems nonsensical.

What are people's thoughts on this?

### LINKED ISSUE #2582: When displaying default values do not display [] when value is null
_v2.0.0-beta5.25306.1_

I have some default values that _can_ be sourced from environment variables if they're present.

For example,

```c#
        var passwordOption = new Option<string?>("--password". "-p", "/p")
        {
            Description = "The password to use.",
            DefaultValueFactory = defaultValue =>
            {
                if (string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("_Password")))
                {
                    return null;
                }

                return Environment.GetEnvironmentVariable("_Password");
            }
        };

```

Currently the help text would display 

```
-p, --password          The password to use. []
```

It would, to my mind, be cleaner if, when the `DefaultValueFactory` returns null that nothing is displayed as the default, because in this case there is no default.

e.g.

```
-p, --password          The password to use.
```

### PR DESCRIPTION
**Pull request by jonsequitur**
This fixes the following issues:

* #2592
* #2582
* #2573

The approach I took to fix #2573 makes `Argument<bool>` and `Option<bool>` have an implicit `DefaultValueFactory`. This change drove changes to the `HelpBuilder` so I also fixed #2582 while I was in there.

It's not obvious to me that this is the right fix, so I thought that the PR would help clarify the discussion.

For example, should other types than `bool` have this behavior of an implicit default value?

### CODE REVIEW

File: src/System.CommandLine/Argument{T}.cs [hunk 1]
```diff
@@ -76,6 +93,11 @@ public Argument(string name) : base(name)
         {
             if (DefaultValueFactory is null)
             {
+                if (IsBoolean())
+                {
+                    return false;
+                }
```
[the remark this answers is not in the document]
Comment (jonsequitur) [reply src/System.CommandLine/Argument{T}.cs:99]: This is dead code in any case. The actual current behavior matches that expectation.

File: src/System.CommandLine.Tests/System.CommandLine.Tests.csproj [hunk 2]
```diff
@@ -1,7 +1,7 @@
 ﻿<Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
-    <TargetFrameworks>$(TargetFrameworkForNETSDK);$(NetFrameworkCurrent)</TargetFrameworks>
+    <TargetFrameworks>$(TargetFrameworkForNETSDK)</TargetFrameworks>
```
Comment (jonsequitur) [inline src/System.CommandLine.Tests/System.CommandLine.Tests.csproj:4]: @ViktorHofer I was getting the error `error CS0518: Predefined type 'System.Range' is not defined or imported` for usage of index and range syntax for `net481` within this project until I did this. I tried adding the classes directly as well as referencing Microsoft.Bcl.Memory and neither approach worked. 

Is this target framework needed for the tests? (It's not included for the main library.)

Comment (ViktorHofer) [reply src/System.CommandLine.Tests/System.CommandLine.Tests.csproj:4]: The issue is in ApprovalTests: https://github.com/approvals/ApprovalTests.Net/issues/768

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you for fixing all the issues @jonsequitur !

File: src/System.CommandLine.Tests/System.CommandLine.Tests.csproj (hunk 2 above)
Comment (ViktorHofer) [reply src/System.CommandLine.Tests/System.CommandLine.Tests.csproj:4]: We should definitely keep the .NET Framework tests. That validates that the library works correctly on modern .NET and .NET Framework.

Comment (jonsequitur) [reply src/System.CommandLine.Tests/System.CommandLine.Tests.csproj:4]: That would be great. Thanks!

File: src/System.CommandLine/Argument{T}.cs [hunk 3]
```diff
@@ -27,7 +28,23 @@ public Argument(string name) : base(name)
...
+        public Func<ArgumentResult, T>? DefaultValueFactory
+        {
+            get
+            {
+                if (_defaultValueFactory is null)
+                {
+                    switch (this)
+                    {
+                        case Argument<bool> boolArgument:
+                            boolArgument.DefaultValueFactory = _ => false;
```
[the remark this answers is not in the document]
Comment (jonsequitur) [reply src/System.CommandLine/Argument{T}.cs:40]: Agreed, `if` is cleaner. I was considering whether other types should have similar treatment.

File: src/System.CommandLine.Tests/OptionTests.cs [hunk 4]
```diff
@@ -405,6 +469,8 @@ public void Multiple_identifier_token_instances_without_argument_tokens_can_be_p
 
             var result = root.Parse("-v -v -v");
 
+            using var _ = new AssertionScope();
```
[the remark this answers is not in the document]
Comment (adamsitnik) [reply src/System.CommandLine.Tests/OptionTests.cs:472]: > This changes the behavior of the assertions so that all will be evaluated and reported even if the first one fails. Multiple assertions in a test is often considered an antipattern because they can fail independently and failing the test on the first assertion failure loses useful information.
> 
> The `AssertionScope` approach provides a way to make sure all assertion results are reported.

Thanks a lot! It would be great if we could enable it project-wide without a code change (like a csproj setting)

File: src/System.CommandLine.Tests/System.CommandLine.Tests.csproj (hunk 2 above)
Comment (ViktorHofer) [reply src/System.CommandLine.Tests/System.CommandLine.Tests.csproj]: Done
