### PR TITLE
make CommandLineConfiguration mutable, remove CommandLineBuilder

### LINKED ISSUE #1907: Redesign `CommandLineConfiguration` to be mutable and favor properties over constructors
```C#
    public class CommandLineConfiguration 
    {
        // Usability studies have shown that more junior developers get confused by the IntelliSense presentation of methods with many optional parameters.
        // Similar components use get/set properties for the optional ones, and just make the setters throw after a certain point.  For your case
```

### LINKED ISSUE #1920: Move `CommandLineBuilder` into the application framework layer
```C#
namespace System.CommandLine.Builder
{
    public class CommandLineBuilder 
    {
        public CommandLineBuilder(Command rootCommand = null);
        public Command Command { get; }
        public Parser Build()
    }
 
    // All of the things that extend CommandLineBuilder should be instance members on CommandLineBuilder.
    // If UseHelpBuilder is providing namespace-based componentization then it can make sense here, but the type name is bad for it because
    //   a) it says it's extending CommandLineBuilder, but doesn't (necessarily) and b) should have a named purpose, not just "SomethingExtensions".
    public static class CommandLineBuilderExtensions 
    {
         // Is there only one environment variable, or is it multiple?  I feel like I'd expect plurality here, but don't know why.
        public static CommandLineBuilder UseEnvironmentVariableDirective(this CommandLineBuilder builder);
 
        // What happens if this is called twice?  If it's "last writer wins", then "Set" is a better verb than "Use". If it's accumulated, then Add.  Applies to all of the Use- methods.
        public static CommandLineBuilder UseExceptionHandler(this CommandLineBuilder builder, Action<Exception,InvocationContext> onException = null, int? errorExitCode = null);
 
        // The middle overload feels like it must be doing something very different than the other two.  You either need more overloads, or to rename something, or to remove the middle one, or something.
        public static CommandLineBuilder UseHelp(this CommandLineBuilder builder, int? maxWidth = null);
        public static CommandLineBuilder UseHelp(this CommandLineBuilder builder, string[] helpAliases);
        public static CommandLineBuilder UseHelp(this CommandLineBuilder builder, Action<HelpContext> customize, int? maxWidth = null);
        
        // Generic extension methods with no constraints are prohibited, otherwise they apply to object, which is prohibited.
        public static TBuilder UseHelpBuilder<TBuilder>(this TBuilder builder, Func<BindingContext,HelpBuilder> getHelpBuilder);
 
        public static CommandLineBuilder UseLocalizationResources(this CommandLineBuilder builder, LocalizationResources validationMessages);
        public static CommandLineBuilder UseParseDirective(this CommandLineBuilder builder, int? errorExitCode = null);
        public static CommandLineBuilder UseParseErrorReporting(this CommandLineBuilder builder, int? errorExitCode = null);
        public static CommandLineBuilder UseSuggestDirective(this CommandLineBuilder builder);
        
        // Does 0 disable it?  Seems like `int TypoCorrectionLevel { get; set; }` to me; or, if 0 doesn't disable it, make it `int?`
        public static CommandLineBuilder UseTypoCorrections(this CommandLineBuilder builder, int maxLevenshteinDistance = 3);
```

### LINKED ISSUE #1922: Move appropriate `CommandLineBuilder` methods to properties on `CommandLineConfiguration`
```C#
        // Technically "cancel" is a verb, but I feel like the method is actually implying "Set" as the main verb and CancelOnProcessTermination is what the property would be called.
        // So, consider making this a property instead of a method when moving it.
        public static CommandLineBuilder CancelOnProcessTermination(this CommandLineBuilder builder);
        // These Enables also look like properties.
        public static CommandLineBuilder EnableDirectives(this CommandLineBuilder builder, bool value = True);
        public static CommandLineBuilder EnableLegacyDoubleDashBehavior(this CommandLineBuilder builder, bool value = True);
        public static CommandLineBuilder EnablePosixBundling(this CommandLineBuilder builder, bool value = True);
```

### LINKED ISSUE #1924: Consider whether `UseDefaults` is still needed
```C#
        // Wouldn't `new CommandLineBuilder()` already be using defaults? What does this method do?
        // Either needs to be renamed (Reset?) or cut.
        public static CommandLineBuilder UseDefaults(this CommandLineBuilder builder);
```

### LINKED ISSUE #1925: Consider moving `UseVersionOption` to `CommandLineConfiguration` and renaming
```C#
        // As this is basically the only time "Version" appears, I have literally no idea what this means.
        // If it's equivalent to .Add(new Option("version")), then that'd be "AddVersionOption", since the main verb is "Add".
        public static CommandLineBuilder UseVersionOption(this CommandLineBuilder builder);
        public static CommandLineBuilder UseVersionOption(this CommandLineBuilder builder, string[] aliases);
```

### LINKED ISSUE #1926: Consider moving `UseTokenReplacer` to `CommandLineConfiguration` and renaming
```csharp
        // UseTokenReplacer's parameter should obviously be "tokenReplacer", not "replaceToken"
        public static CommandLineBuilder UseTokenReplacer(this CommandLineBuilder builder, System.CommandLine.Parsing.TryReplaceToken replaceToken);
    }
}
```

### LINKED ISSUE #2034: CommandLineBuilder inconsistency?
Invoking the following program with no arguments:

```csharp
using System.CommandLine;
using System.CommandLine.Builder;
using System.CommandLine.Parsing;

internal static class Program
{
    //private static Task<int> Main(string[] args) =>
    //    new CommandLineBuilder(CreateRootCommand())
    //    .Build()
    //    .InvokeAsync(args);

    private static Task<int> Main(string[] args) =>
        CreateRootCommand().InvokeAsync(args);

    private static Command CreateRootCommand()
    {
        var rootCommand = new RootCommand("Specifying a sub-command is required.");
        var fooCommand = new Command("foo");
        rootCommand.Add(fooCommand);
        return rootCommand;
    }
}
```

results in a red error message that says "Required command was not provided." followed by the program help text, and the program returns an error exit code.

However, if I replace the `Main` method above with the commented-out `Main` method and invoke the program with no arguments, then nothing appears and the program returns a successful exit code.

Is this discrepancy intentional? If so, how do I make the `CommandLineBuilder` version behave the same as the non-`CommandLineBuilder` version?

This is using System.CommandLine 2.0.0-beta4.22272.1

Thanks!

### LINKED ISSUE #2046: More design questions
We are soon going to have another internal round of design discussion for System.CommandLine. I am sharing the list of open questions here so everyone can share their feedback.

# Symbols

## Description

Symbol.Description does not need to be `virtual`: https://github.com/dotnet/command-line-api/pull/2045

Every symbol can provide the description in the `ctor`.

## HelpName

When Argument is parsed, we use its position rather than name. But when we want to refer to it, for example when displaying help, it may need a name.

Currently the type has both `Name` and `HelpName`. Why does `Argument` need both?

## Arity

Can anyone provide a better name?

## Parse(string), Parse(string[])

Both methods are used only for testing purposes in System.CommandLine. They don't provide any possibility to customize the configuraiton used for parsing. They can be easily replaced with one liner:

```cs
new CommandLineBuilder(new Command() { argument }).UseDefaults().Build().Parse($input);
```

I believe that we should remove them or made them internal.

## Validators

Currently a validator is an `Action<ArgumentResult>`. What I don't like about this design is the fact that it allows for modificaitons of the `ArgumentResult`.

Example:

```cs
argument.Validators.Add(argumentResult => argumentResult.OnlyTake(3));
```

It's hard to propose a better design, as some validators need more than just `SymbolResult.Tokens`. Example: validator may want to call `GetValueOrDefault` to validate parsed value.

## ctors

`Argument<T>` provides multiple ways of setting default value: as `T`, `Func<T>` and `Func<ArgumentResult, T>`

```cs
public Argument(Func<T> defaultValueFactory)
    
public Argument(
    string name,
    T defaultValue,
    string? description = null)

public Argument(
    string? name,
    Func<ArgumentResult, T> parse,
    bool isDefault = false,
    string? description = null)
```

What I don't like is the fact that the last ctor requires the user to define whether given `Func<ArgumentResult, T>` is a default value provider or a custom parser. It's confusing.

My understanding is that we need custom parser for complex types and default values for all kinds of types. IMO the latter is way more common than the first.

Do we really need a default value provider that uses `ArgumentResult` as an input?
Do we really need the default value to be lazily provided?

How about having just one ctor:

```cs
public Argument(
    string? name = null,
    string? description = null
    T? defaultValue = null,
    Func<ArgumentResult, T> customParser = null)
```

## SetDefaultValue, SetDefaultValueFactory

Same as above, there are 3 different ways of setting default value:

```cs
public void SetDefaultValue(T value)
public void SetDefaultValueFactory(Func<T> defaultValueFactory)
public void SetDefaultValueFactory(Func<ArgumentResult, T> defaultValueFactory)
```

I would stick with two:

```cs
public void SetDefaultValue(T value)
public void SetCustomParser(Func<ArgumentResult, T> customParser)
```

## AcceptLegalFilePathsOnly, AcceptLegalFileNamesOnly

These instance methods are usefull only for argument of `string`, `FileInfo` and arrays of these two.

Currently they can be used for all kinds of `T`:

```cs
Argument<int> portNumber = new ();
portNumber.AcceptLegalFilePathsOnly();
```

Does anyone have a better idea how to make sure they don't get suggested/used for `T` other than the ones it makes sense for?

We could of course introduce them as extension method of `Argument<string>`, `Argument<string[]>`, `Argument<FileInfo>`, `Argument<FileInfo[]>`, but I doubt it would be accepted by BCL review board.

## IdentifierSymbol

From my point of view the existence of this type is an implementation detail (it's a Symbol with Aliases).

I need to discuss this case with Jeremy.

## ArgumentHelpName

Similar to `Argument.Name`: the users have the possibility to set `Name` for `Option`. Do we really need this property? We use aliases for parsing and it seems like Name is exactly what we need for help.

## IsGlobal

This property is currently `internal`, but we should expose it.

We need a better name. Ideas?

## Parse(string), Parse(string[])

Same as `Arugment.Parse`: do we really need these methods to be public?

## ctors

Same as for `Argument<T>`: we need a better way to distinguish default value provider and custom parser.

## Command.Children

Command exposes `Argument`, `Options`, and `Subcommands` properties.

It also implements `IEnumerable<Symbol>` and `Add(Symbol)` to support a very common duck typing C# syntax:

```cs
Command cmd = new ()
{
    new Argument<int>() // uses duck typing and calls Command.Add(Symbol).
};
```

Do we really need to expose `IEnumerable<Symbol> Children` on top of that? It seems redundant to me.

## AddGlobalOption

If we made `Option.IsGlobal` public, we can remove this method, so users can do:

```cs
command.Options.Add(new Option<bool>("some") { IsGlobal = true });
```

## TreatUnmatchedTokensAsErrors

Does it make sense to make this setting specific to given command? Should it become a part of `CommandLineConfiguration`?

## Parse

Command has no `Parse` instance methods, but it does have an extension method.

IMO we should make it an instance method with optional `CommandLineConfiguration` argument to make it easier to discover the configurability of parsing:

```cs
ParseResult Parse(CommandLineConfiguration? configuration = null)
```

## RootCommand

Currently it exposes only two public methods:

```cs
public static string ExecutablePath => Environment.GetCommandLineArgs()[0];

public static string ExecutableName => Path.GetFileNameWithoutExtension(ExecutablePath).Replace(" ", "");
```

This information can be easily obtained by System.CommandLine users (by using `System.Environment` class).

Currently the only difference with `Command` is that it does not allow for setting custom alias (which should be ultra rare). Could this be achieved without a dedicated `RootCommand` type? I want to reduce the number of concepts the users need to get familiar with. Better perf (fewer types to load and JIT) is just a side effect of that,

# Parsing

## CommandLineConfiguration

This type provides multiple internal properites and some public properties. All of them are readonly. Should we make them mutable to avoid the need of having a builder type?

## EnableEnvironmentVariableDirective, EnableSuggestDirective, EnableDirectives

If we expose all the internal properties, are we going to introduce a new property for every new directive?

What are the alternatives other than creating dedicated directive types and adding `Command.Directives` property?

## EnableTokenReplacement

Why is it enabled by default?

## TokenReplacer

Why do we need custom token replacers? What do users customize other than supporting comments in the response files?

Perhaps we should expose an enumeration and provide default implementation?

```
enum ResponseFiles
{
    Disabled,
    Enabled,
    SpecificStandardName1,
    SpecificStandardName2,
    
}

config.ResponseFiles = ResponseFiles.Disabled;
```

What I don't like about the current design is that `InvokeAsync` performs parsing which can perform a blocking call when reading the response file:

https://github.com/dotnet/command-line-api/blob/1bc03fed713b0b10455942d9f8eeab371d519cba/src/System.CommandLine/Parsing/StringExtensions.cs#L386

If we just provide an enumeration, it would be easier to do the right thing (call async APIs for async invocation, pass CancellationToken etc).

## LocalizationResources

In BCL, `System.*` libraries that need localization provide their own set of resource files, configure automation with https://github.com/dotnet/arcade/blob/main/Documentation/OneLocBuild.md and **don't expose a possibility to customize the transaltions**. This type needs to be removed / made internal.

Please see https://github.com/dotnet/command-line-api/pull/2041 for more details.

## CommandLineBuilder

The type name is confusing to me. It builds a parser and configuration and I would expect it to be called `CommandLineConfigurationBuilder`. But perhaps we can remove it if we make `CommandLineConfiguration` mutable?

It defines almost no public methods, but `CommandLineBuilderExtensions` provides plenty of its extensions.

## Properties are not always enough

Not every configuration can be expressed with a single property. Some methods allow for additional customization.

For example `UseParseErrorReporting` allows for enabling the parse error reporting and setting a custom exit code for parsing errors:

```cs
public static CommandLineBuilder UseParseErrorReporting(
    this CommandLineBuilder builder,
    int errorExitCode = 1)
```

## RegisterWithDotnetSuggest

The current design has plenty of flaws. One of them is major perf hit for default config (creating files and starting new process to register).

We most likely need a separate meeting dedicated to dotnet suggest. Who should be invited?

## UseDefaults

Before we find a proper solution for `RegisterWithDotnetSuggest`, can we disable it by default?

## UseExceptionHandler

Curent API:

```cs
public static CommandLineBuilder UseExceptionHandler(
    this CommandLineBuilder builder,
    Action<Exception, InvocationContext>? onException = null,
    int? errorExitCode = null)
```

In my opinion exception handler should always return an int. It would make the config simpler and easier to discover the possibility to set custom exit code.

```cs
public static CommandLineBuilder UseExceptionHandler(
    this CommandLineBuilder builder,
    Func<Exception, InvocationContext, int>? onException = null);
```

## AddMiddleware

Middleware is VERY powerfull. After https://github.com/dotnet/command-line-api/pull/2043 we are close to having 0 middleware by default (it's expensive).

I need to make a research and see why our users provide custom middleware. Just to make sure it's not just a mechanism for workarounding our limitations like missing configuraiton etc.

## UseHelp

I've not analysed this part of S.CL yet. I will have comments in the near future.

## Parser

First of all I believe that this type is simply hard to discover. The only state it has is `CommandLineConfiguration`. To make `CommandLineConfiguration` more discoverable I would make `Parser` static with just one method:

```cs
static class Parser
{
    static PareResult Parse(string[] args, CommandLineConfiguration configuration = default);
}
```

We also need to rename it to `CliParser` to avoid conflicts with dozen other parsers ;)

## Directives

Currently the only way for the users to implement custom directives is enabling directives parsing in the config and using this property to get parsed output.

The problem is that if the users want to perform any custom action based on the directive input like setting custom culture: `[culture pl]` they need to use Middleware (expensive).

Should we expose a dedicated `Directive` symbol type?

```cs
class Directive : Symbol
{
    Directive(string name, Action<string> onParsed);
}
```

## UnmatchedTokens

The `Tokens` property returns a collection of `Token` type. `UnmatchedTokens` returns a collection of `string`s. Why don't we expose full information?

## GetValue

Do we need both the generic and non-generic overloads?

```cs
object? GetValue(Option option) 
T? GetValue<T>(Option<T> option)
object? GetValue(Argument argument)
T GetValue<T>(Argument<T> argument)
```

## SymbolResult

SymbolResult and it's entire family LGTM after recent changes.

### LINKED ISSUE #2057: Make CommandLineConfiguration mutable
- [ ] #2054 needs to be implemented first, as it's not clear whether we will be able to remove the `CommandLineBuilder` type. `Builder` types are the only types in BCL that are allowed to use fluent APIs (returning reference to `this` to allow for calls chaining) and I am currently not sure if we are going to be able to repsent all configuration options as properties (many extension methods set two things at a time).
- [ ] #2056 needs to be implemented first as it will have great impact on how `Directives` will be configured. We don't want to have `EnableDirectiveXYZ` property for every Directive
- [ ] make all the internal fields and properties public, with nice names
- [ ] make all the public properties mutable

### LINKED ISSUE #2101: New Config proposal
One of our goals is simplyfing the configuration, making it easier to discover and use.

This can be achieved by making the configuration mutable (no need for a dedicated builder) and making it an optional argument for `Command.Parse` (this has already happened).

My current idea is following:

```cs
public class CliConfiguration
{
    public CliConfiguration(Command command)
    {
        Command = command;
        Directives = new()
        {
            new SuggestDirective()
            // I am not sure whether we should enable other Directives by default
            // new EnvironmentVariablesDirective()
            // new ParseDirective()
        };
    }

    public Command Command { get; }

    public bool EnablePosixBundling { get; set; } = true;

    public bool EnableDefaultExceptionHandler {  get; set; } = true;

    public bool EnableTypoCorrections { get; set; } = false;

    public TimeSpan? ProcessTerminationTimeout { get; set; } = TimeSpan.FromSeconds(2);

    public int ParseErrorExitCode { get; set; } = 1;

    public TryReplaceToken? ResponseFileTokenReplacer { get; set; } = StringExtensions.TryReadResponseFile;

    public List<Directive> Directives { get; }
}
```

How to disable signaling and handling of process termination via a `CancellationToken`? Set `ProcessTerminationTimeout` to `null`.

How to disable default response file token replacer? Set `ResponseFileTokenReplacer` to `null`.

How to customize exception handler? Set `EnableDefaultExceptionHandler` to `false` and catch the exceptions on your own:

```cs
CliConfiguration config = new(command) { EnableDefaultExceptionHandler = false };
ParseResult parseResult = command.Parse(args, config);

try
{
    return parseResult.Invoke();
}
catch (Exception ex)
{
    // custom exception handler
}
```

The alternative for customizing the `ParseErrorExitCode` is following:

```cs
ParseResult parseResult = command.Parse(args);

if (parseResult.Errors.Any())
{
    return $customValue;
}
```

The most tricky part is how `HelpOption` and `VersionOption` should be enabled and disabled. Currently, the config builder just adds them to the provided `Command` options list:

https://github.com/dotnet/command-line-api/blob/3b5c4beb3e3d09702ba7d05b098f3594759188fd/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs#L336-L351

I don't like it, as it's a side effect. But on the other hand, I don't have an ideal alternative.

Possible solutions:

## Expect the users to add them in explicit way.

```cs
command.Options.Add(new HelpOption());
command.Options.Add(new VersionOption());
```

Advantage(s): no magic, everything is crystal clear, perf.
Disadvantage(s): help would be not enabled by default.

## Create every command with Help and Version options added by default

```cs
public Command(string name, bool addDefaultOptions = true)
{
    if (addDefaultOptions)
    {
        Options.Add(new HelpOption());
        Options.Add(new VersionOption());
    }
}
```

Advantage(s): help enabled by default.
Disadvantage(s): Hard to customize help (find, cast & customize or replace) I expect that `Version` makes sense only for the root command, it would pollute subcommands.

Perhaps it would make more sense for `RootCommand`?
Maybe the argument should not be optional, so everyone who creates a Command would need to think about it?

## Expose the options as part of Config type, add them the root Command when parsing

```cs
public class CliConfiguration
{
    public HelpOption? HelpOption { get; set; } = new ();
    
    public VersionOption? VersionOption { get; set; } = new ();
}
```

Advantage(s): quite easy to discover and configure, enabled by default.
Disadvantage(s): side effect of adding them to the root command (but so far nobody complained about it beside me?)

Do we really need `VersionOption` enabled by default?

## Add a list of default Options to Config, similarly to Directives

```cs
public class CliConfiguration
{
    public List<Option> Options { get; }
}
```

Advantage(s): quite easy to discover, consistent with Directives
Disadvantage(s): hard to configure a specific option (find HelpOption, cast it and then set the builder), side effect of adding them to the root command 

@jonsequitur @KathleenDollard @Keboo @KalleOlaviNiemitalo please provide feedback

### LINKED ISSUE #2111: CancelOnProcessTermination no longer enabled by default
Before https://github.com/dotnet/command-line-api/pull/2044, the `CancellationToken` was hooked in the default configuration.

Now, you need to explicitly call `CancelOnProcessTermination`.

@adamsitnik is this an intentional change?

### LINKED ISSUE #2117: Allow new HelpOption("--help") without aliases
Now that <https://github.com/dotnet/command-line-api/pull/2102> in System.CommandLine 2.0.0-beta4.23172.1 made System.CommandLine.Help.HelpOption public, it would be handy if I could create an instance of HelpOption by using just `new HelpOption("--help")` rather than `new HelpOption("--help", aliases: null)`. That could be implemented in any of the following ways:

 - new constructor: `public HelpOption(string name)`
 - optional parameter: `public HelpOption(string name, string[]? aliases = null)`
 - params: `public HelpOption(string name, params string[] aliases)`. That would be consistent with the Option\<T\> constructor.

I don't like using `new HelpOption("--help", null)` with an unnamed `null` argument because its purpose would not be immediately obvious to people reading the code. `new HelpOption("--help", Array.Empty<string>())` is quite clear too but more verbose than a named argument.

(System.CommandLine.Help.VersionOption is not public yet.)

### PR DESCRIPTION
**Pull request by adamsitnik**
fixes #2101

fixes #1907
fixes #1920
fixes #1922
fixes #1924
fixes #1925 
fixes #1926
fixes #2034
closes #2046 (the last element from the TODO list)
fixes #2057
fixes #2111
fixes #2117

### CODE REVIEW

File: src/System.CommandLine/ChildList.cs [hunk 1]
```diff
@@ -37,7 +38,35 @@ public ChildList(Command parent)
         public void Add(T item)
         {
             item.AddParent(_parent);
+
+            if (_children.Count > 0 && _parent is RootCommand)
```
Comment (adamsitnik) [inline src/System.CommandLine/ChildList.cs:42]: `RootCommand` ctor adds `HelpOption` and `VersionOption` by default now. Users might want to customize it like that:

```cs
RootCommand rootCommand = new()
{
    new VersionOption("-v", "-version"),
};
```

In order to avoid duplicates, this method checks if a help option or version option already exists. If it does, it overrides it.

File: src/System.CommandLine/CommandLineConfiguration.cs [hunk 2]
```diff
@@ -19,108 +18,76 @@ public class CommandLineConfiguration
...
+        /// Initializes a new instance of the <see cref="CommandLineConfiguration"/> class.
         /// </summary>
-        internal readonly Func<Exception, InvocationContext, int>? ExceptionHandler;
+        /// <param name="rootCommand">The root command for the parser.</param>
+        public CommandLineConfiguration(Command rootCommand)
+        {
+            RootCommand = rootCommand ?? throw new ArgumentNullException(nameof(rootCommand));
+            Directives = new()
+            {
+                new SuggestDirective()
```
Comment (adamsitnik) [inline src/System.CommandLine/CommandLineConfiguration.cs:29]: I was not sure which directives should be enabled by default, it's an open question.

I have not enabled all of them, as it would cause a perf hit for the users.

File: src/System.CommandLine.Tests/VersionOptionTests.cs [hunk 3]
```diff
@@ -156,15 +158,17 @@ public void Version_option_is_not_added_to_subcommands()
...
-                         .UseVersionOption()
-                         .UseVersionOption()
-                         .Build();
-            configuration.Output = new StringWriter();
+            // The RootCommand ctors adds VersionOption by default.
+            // Users might not know if or just want to customize it.
+            RootCommand commandWithDuplicates = new()
+            {
+                new VersionOption(),
+                new VersionOption(),
```
Comment (jonsequitur) [inline src/System.CommandLine.Tests/VersionOptionTests.cs:166]: Shouldn't this be an error because of the symbol identifier collision?

I think the expectation with the builder is that it's idempotent, but I don't think I have the same expectation with `Command.Add` since we're enforcing name and alias uniqueness.

File: src/System.CommandLine/ChildList.cs (hunk 1 above)
Comment (jonsequitur) [reply src/System.CommandLine/ChildList.cs:42]: I think it might be less surprising to just ask people to remove the other instance, especially given that the `HelpAction` is  also customizable and is probably the more common path to customizing help.

Comment (adamsitnik) [reply src/System.CommandLine/ChildList.cs:42]: @jonsequitur you are right, I've removed this logic and updated the tests

File: src/System.CommandLine.Tests/VersionOptionTests.cs [hunk 4]
```diff
@@ -155,33 +155,17 @@ public void Version_option_is_not_added_to_subcommands()
...
         {
-            RootCommand rootCommand = new()
+            RootCommand rootCommand = new();
+
+            for (int i = 0; i < rootCommand.Options.Count; i++)
             {
-                new VersionOption("-v", "-version"),
-            };
+                if (rootCommand.Options[i] is VersionOption)
+                    rootCommand.Options[i] = new VersionOption("-v", "-version");
```
Comment (jonsequitur) [inline src/System.CommandLine.Tests/VersionOptionTests.cs:166]: This is a general comment and doesn't need to block merging.

The API through beta4 treated the arguments to `Option<T>` such that  `new VersionOption("-v", "-version")` would indicate `-version` is the description.

The beta5 API understands this as setting `Name` to `-v` and using `-version` as an alias. In general usage though, `-version` would be the name (being longer) and `-v` would be the alias.

Two observations:

* I've found this to be a gotcha in upgrading my code.
* This usage in tests, while perfectly valid, might mislead about the way in which the API is typically used.

**Review by jonsequitur — APPROVED** [review]
