### PR TITLE
Fix #2210

### LINKED ISSUE #2210: Option with nullable type causes InvalidOperationException when parsing invalid value
## Problem
If I use a nullable type for an `Option<T>` (which is useful for determining whether the option was specified at all), and an invalid value is provided to that Option on the command line, the application will crash with an InvalidOperationException. It does not crash if the Option type is not nullable.

I will freely admit that using a nullable type for an Option may not be the "correct" approach; it _seemed_ like the most expedient way to identify whether an option was specified by the user. 

## Example for Reproducing
For example, invoking the following application with arguments "--test ouch" will crash:
```csharp
using System.CommandLine;
using System.CommandLine.Builder;
using System.CommandLine.Parsing;

RootCommand rootCommand = new("example-app");
Option<bool?> testOption = new("--test");
rootCommand.AddOption(testOption);
rootCommand.SetHandler(rootHandler, testOption);
CommandLineBuilder builder = new(rootCommand);
return builder.Command.InvokeAsync(args).Result;

async Task<int> rootHandler(bool? test)
{
	Console.WriteLine("In handler");
	return 0;
}
```

```
Unhandled exception: System.InvalidOperationException: Cannot parse argument 'ouch' for option '--test' as expected type 'System.Boolean'.
   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
   at System.CommandLine.Parsing.SymbolResult.GetValueForOption[T](Option`1 option)
...
```

But if I change it to `Option<bool>` instead of `Option<bool?>` (and the corresponding change to rootHandler), then there's no crash:

```
'ouch' was not matched. Did you mean one of the following?
-h
Unrecognized command or argument 'ouch'.

Description:
  example-app
...
```

## Proposed Solutions

1. Support nullable types for Option so they are handled more like "regular" types from an end user standpoint.
2. Block the use of nullable types for Option (provided there is a different/better way to determine whether an option was specified).

### PR DESCRIPTION
**Pull request by jonsequitur**
This fixes #2210. The issue was that `bool` parsing had a special case in place so that it doesn't consume the following token if that token can't be parsed as a bool. This lets the unparseable token by consumed by a different symbol, which is typically the intent.

The fix includes `bool?` in that special case.

### CODE REVIEW

**Review by Keboo — APPROVED** [review]

File: src/System.CommandLine/ParseResult.cs [hunk 1]
```diff
@@ -180,12 +181,12 @@ public IReadOnlyList<string> UnmatchedTokens
...
             }
 
-            static T? Convert(ArgumentConversionResult validatedResult)
+            static T Convert(ArgumentConversionResult validatedResult)
             {
                 var convertedResult = validatedResult.ConvertIfNeeded(typeof(T));
 
-                if (validatedResult.Result == ArgumentConversionResultType.Successful
-                    && convertedResult.Result == ArgumentConversionResultType.NoArgument)
+                if (validatedResult is { Result: ArgumentConversionResultType.Successful }
```
Comment (adamsitnik) [inline src/System.CommandLine/ParseResult.cs:188]: do you find this syntax more readable?

**Review by adamsitnik — COMMENTED** [review]
Thank you for fixing the bug!

File: src/System.CommandLine/ParseResult.cs (hunk 1 above)
Comment (jonsequitur) [reply src/System.CommandLine/ParseResult.cs:188]: I prefer it as a best practice because the behavior of `==` can be changed by operator overloading.

File: src/System.CommandLine/Parsing/ParseOperation.cs [hunk 2]
```diff
@@ -246,9 +246,10 @@ private void ParseOptionArguments(OptionResult optionResult)
                         break;
                     }
                 }
-                else if (argument.ValueType == typeof(bool) && 
+                else if ((argument.ValueType == typeof(bool) || argument.ValueType == typeof(bool?))  &&
```
[the remark this answers is not in the document]
Comment (jonsequitur) [reply src/System.CommandLine/Parsing/ParseOperation.cs:249]: Thanks for pointing it out! I've updated to use that in my other PR.
